export const path = {
  correspondence: "/correspondence",
  sentence: "/sentence",
  login: "/login",
  profile: "/profile",
  speaking: "/speaking",
  teacherRoom: "/teacher-room",
  createLesson: "/create-lesson",
  classroom: "/classroom",
  editClass: "/edit-class",
  lessonsList: "/lessons-list",
  lessonResults: "/lesson-results",
  poem: "/poem",
  reading: "/reading",
};
